### ISSUE TITLE
TODO: Add testing example's 

### ISSUE THREAD

**Issue by bsliran** [bsliran/angular2-meteor-base#2]
Add testing examples for both client and server side
- [x] Tests framework + TypeScript
- [x] Mocha + Chai
- [x] Tests main file (initiliazer.test.ts)
- [x] Create Polyfills for angular2 framework base
- [x] DemoComponent tests (with Angular utils)
- [x] DemoDataService tests (with Meteor utils)
- [x] Server-side tests

**Comment by dotansimha** [comment]
Tests polyfills are here: https://github.com/dotansimha/angular2-meteor-tests-polyfills
We need them because Angular 2 assumes that when you create the tests providers, it also have `jasmine` global so I needed to create a polyfill that mocks this.
